=== whoopsLALA/task/schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--W3C Schema generated by XMLSpy v2013 (http://www.altova.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="students">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="student" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="student">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="name"/>
				<xs:element ref="gender"/>
				<xs:element ref="age"/>
			</xs:sequence>
			<xs:attribute name="StuId" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:byte">
						<xs:enumeration value="1"/>
						<xs:enumeration value="2"/>
						<xs:enumeration value="3"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="name">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="张三"/>
				<xs:enumeration value="李四"/>
				<xs:enumeration value="王二"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="gender">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="女"/>
				<xs:enumeration value="男"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="age">
		<xs:simpleType>
			<xs:restriction base="xs:byte">
				<xs:enumeration value="19"/>
				<xs:enumeration value="20"/>
				<xs:enumeration value="21"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
</xs:schema>

=== whoopsLALA/task/demo1.xml
<?xml version="1.0" encoding="UTF-8"?>
<students xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///C:/Users/%e9%bb%84%e9%94%a6%e9%94%a6/Desktop/xmlwenjian/schema.xsd">
	<student StuId="1">
		<name>张三</name>
		<gender>男</gender>
		<age>20</age>
	</student>
	<student StuId="2">
		<name>李四</name>
		<gender>女</gender>
		<age>19</age>
	</student>
	<student StuId="3">
		<name>王二</name>
		<gender>男</gender>
		<age>21</age>
	</student>
</students>
